### ISSUE TITLE
App signature contains references to .git files

### ISSUE THREAD

**Issue by silviuchingaru** [SpicyWeb-de/nextcloud-user-ispconfig#10]
After update to NextCloud 22, the user_ispconfig app fails to pass signature checking in https://[cloud domain]/settings/admin/overview with missing files because appinfo/signature.json contains hash-es of .git directory files. 
Those hash-es should be included only for development version but not for NextCloud app catalog.

**Comment by conrad784** [comment]
I help up this upgrade until now, but I just did the upgrade and I do not see any issues? Could you elaborate, what versions you are on?

**Comment by qroac** [comment]
Sorry for long time not working on this project.
I just released a new version containing PR #17 that should no longer contain git files in signatures
