### ISSUE TITLE
Version for Nextcloud 23 missing

### ISSUE THREAD

**Issue by conrad784** [SpicyWeb-de/nextcloud-user-ispconfig#12]
After reading https://github.com/nextcloud/server/issues/27846 it seems to be like only the valid versions have to be increased as there are no breaking changes.

It would be nice if https://github.com/SpicyWeb-de/nextcloud-user-ispconfig/issues/10 could be resolved in the same update.

**Comment by blackd** [comment]
Just changing the manifest fixes it. Also works for 24

**Comment by CaptainBalou** [comment]
> Just changing the manifest fixes it. Also works for 24

Could you explain how to do that?

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by CaptainBalou** [comment]
@p-bo But this would nevertheless need that the maintainer of the project to get involved but I think he's very busy with other projects/tasks. 😳

**Comment by blackd** [comment]
TBH between 22 and 24 the only change is in the manifest... and making new release. So not that time consuming.

If I had any idea of PHP I would have forked this already...

**Comment by CaptainBalou** [comment]
@blackd Same here. Thanks to your previous comment I searched for the manifest and changed it to be able to use it in 24. But there may come up a release which that won't work anymore. And also having this plugin offered in the plungin store is super convenient. So I would love to see these changes been commited. But as always this is all depending on priorities and I can understand that there sometimes are times were other things have to get higher priority. But maybe it would be possible to let other contributors get some permission to be allowed to commit their own changes here. I don't know. Whatever would be there the decision has to be taken by the owner.

**Comment by blackd** [comment]
works with 25.x 
if someone is interested

**Comment by CaptainBalou** [comment]
I use it with 25.0.3. Works pretty good. No malfunction.

**Comment by qroac** [comment]
Sorry for not working on this for a long time.
I just released a new verison with changes for NC 27 made by contributors that raised the version requirement to NC 27
