### ISSUE TITLE
Compatibility to NC20

### ISSUE THREAD

**Issue by conrad784** [SpicyWeb-de/nextcloud-user-ispconfig#2]
Hi, since NC20 is now in the production branch, I wonder if you will be releasing a compatible version of this plugin.

**Comment by qroac** [comment]
Ooops. Seems I forgot to release it for NC20.
Will do so in the next days.
For the meantime, if you have a local admin account as fallback, you can upgrade and just enable the user_ispconfig app.
I already use it on NC20, just forgot to publish it.
Shame on me :see_no_evil:

**Comment by qroac** [comment]
Released as compatible with NC20
Sorry for the delay
