### ISSUE TITLE
"The appinfo/database.xml file is not longer supported" after upgrade to NC 22 the app can't be activated

### ISSUE THREAD

**Issue by frankbootmaker** [SpicyWeb-de/nextcloud-user-ispconfig#6]
Hi,

after I upgraded to NC 22 I wanted to re-activate the nextcloud-user-ispconfig app but got the following error message:
"The appinfo/database.xml file is not longer supported."

Could you please fix the app to meet the requirements of NC22?
I think this is a great app and was working for me flawlessly with ISPConfig ever since I installed it... !

I have currently the latest, 0.4.9 version installed on the recently upgraded NC 22 system.

Thank you,
Feri

**Comment by X-Wizard** [comment]
Hi,

Is there any status update too upgrade this interface for NC22?

Thanks in advance

John

**Comment by qroac** [comment]
Thanks for the PR @conrad784
I'll try to free some time next week to push an update to the store.

Sorry for the long delay folks. I'm currently very occupied by my work for an early-stage StartUp and have less time for other projects than I'd like to have. If any of you are willing to participate in this plugin, please submit a PR with your changes.
